use onDidAddTextEditor
To avoid error on startup: 

 TypeError: undefined is not an object (evaluating 'nova.workspace.activeTextEditor.onWillSave')

This only happens on normal startup but not when in development mode and using 'activate project as extension' because the editor object is already valid then.

Hopefully this fixes it, but it is hard to test since development extensions are never active on startup